# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# News API
# Your API key is: 5155bc1072714d8c94bd332c3f7aaa88
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb4476335b2fc65e2483de58364ef210882ae445b9626151848cfda04ffa0c99e58780574b9ab22ce7f412a641f255dd7c7d1598f7cfe09b11f08a49c0e952d6
  super_secret_key: a1B2c3D4e5F6
test:
  secret_key_base: fa75f4777c6cf7bae7a3e95d648bf15d4bc507794e549f02dabc424425f11524f216a36f755d9f35a9fa47c9ddbe3658f9f3c1f454bf5abdb218ed8ac166bb52
  super_secret_key: a1B2c3D4e5F6
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
super_secret_key: <%= ENV["SUPER_SECRET_KEY"] %>
